apiVersion: v2
name: longhorn-wrapper
description: Wrapper chart for Longhorn
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: longhorn
    version: 1.7.2
    repository: https://charts.longhorn.io
