apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: monthly-backup
  namespace: longhorn-system
spec:
  cron: "0 3 1 * *"
  task: backup
  groups:
  - default
  retain: 3
  concurrency: 1
