apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-registries
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: argocd-image-updater-registries
    creationPolicy: Owner
    template:
      data:
        ghcr: "{{ .ghcr_username }}:{{ .ghcr_token }}"
        dockerhub: "{{ .dockerhub_username }}:{{ .dockerhub_token }}"
  data:
    - secretKey: ghcr_username
      remoteRef:
        key: argocd-image-updater/ghcr
        property: username
    - secretKey: ghcr_token
      remoteRef:
        key: argocd-image-updater/ghcr
        property: token
    - secretKey: dockerhub_username
      remoteRef:
        key: argocd-image-updater/dockerhub
        property: username
    - secretKey: dockerhub_token
      remoteRef:
        key: argocd-image-updater/dockerhub
        property: token
