apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-creds-github
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: repo-creds-github
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: "https://github.com/nsudhanva"
        username: "{{ .git_username }}"
        password: "{{ .git_token }}"
  data:
    - secretKey: git_username
      remoteRef:
        key: argocd/repo-creds
        property: username
    - secretKey: git_token
      remoteRef:
        key: argocd/repo-creds
        property: token
