apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
  - secretKey: client_id
    remoteRef:
      key: tailscale/operator-oauth
      property: client_id
  - secretKey: client_secret
    remoteRef:
      key: tailscale/operator-oauth
      property: client_secret
