apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: external-secrets-metrics
  namespace: external-secrets
  labels:
    app.kubernetes.io/instance: external-secrets
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - external-secrets
