apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: alertmanager-telegram
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: telegram/bot
        property: token
    - secretKey: chat-id
      remoteRef:
        key: telegram/bot
        property: chat_id
