apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  selector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
      - metrics
      - server
      - repo-server
      - applicationset-controller
      - notifications-controller
  endpoints:
  - port: metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - argocd
