apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gmail-classifier
resources:
- namespace.yaml
- openrouter-secret.yaml
- secret-primary.yaml
- cronjob-primary.yaml
- secret-secondary.yaml
- cronjob-secondary.yaml
- secret-tertiary.yaml
- cronjob-tertiary.yaml
