apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gmail-classifier
resources:
  - namespace.yaml
  - secret.yaml
  - secret-family.yaml
  - openrouter-secret.yaml
  - cronjob.yaml
  - cronjob-family.yaml
