apiVersion: apps/v1
kind: Deployment
metadata:
  name: technitium
  namespace: technitium
  labels:
    app: technitium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technitium
  template:
    metadata:
      labels:
        app: technitium
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: technitium
          image: technitium/dns-server:latest
          ports:
            - containerPort: 5380
              name: web
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - name: config
              mountPath: /etc/dns
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: technitium-config
