apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: technitium-admin
  namespace: technitium
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: technitium-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: technitium/admin
        property: admin-password
    - secretKey: admin-user
      remoteRef:
        key: technitium/admin
        property: admin-user
