apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-config
  namespace: technitium
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
