apiVersion: batch/v1
kind: CronJob
metadata:
  name: tailscale-dns-updater
  namespace: tailscale-dns
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          serviceAccountName: tailscale-dns-updater
          restartPolicy: OnFailure
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          nodeSelector:
            kubernetes.io/hostname: legion
          containers:
          - name: updater
            image: alpine:3.21.5
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              set -eu
              apk add --no-cache curl ca-certificates >/dev/null
              URL="https://dl.k8s.io/release/v1.34.3/bin/linux/amd64"
              curl -sSL -o /tmp/kubectl "${URL}/kubectl"
              curl -sSL -o /tmp/kubectl.sha256 "${URL}/kubectl.sha256"
              echo "$(cat /tmp/kubectl.sha256)  /tmp/kubectl" | sha256sum -c - >/dev/null
              chmod +x /tmp/kubectl
              NS="tailscale"
              gateway_ip="$(/tmp/kubectl -n "$NS" get gateway tailscale-gateway \
                -o jsonpath='{.status.addresses[?(@.type=="IPAddress")].value}')"
              if [ -z "$gateway_ip" ]; then
                echo "gateway IP not found"
                exit 1
              fi
              cat <<EOF | /tmp/kubectl -n tailscale-dns apply -f -
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: tailscale-dns
                namespace: tailscale-dns
              data:
                Corefile: |
                  sudhanva.me:53 {
                      errors
                      health
                      ready
                      reload
                      template IN A {
                          answer "{{ .Name }} 60 IN A ${gateway_ip}"
                      }
                      forward . 1.1.1.1 1.0.0.1
                      cache 30
                  }
              EOF
