apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-dns-updater
  namespace: tailscale
rules:
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  resourceNames:
  - tailscale-gateway
  verbs:
  - get
