apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      nodeSelector:
        gpu.nvidia.com/present: "true"
      runtimeClassName: nvidia
      containers:
        - image: nvcr.io/nvidia/k8s-device-plugin:v0.20.0
          name: nvidia-device-plugin-ctr
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
            - name: NVIDIA_DRIVER_ROOT
              value: /driver-root
            - name: LD_LIBRARY_PATH
              value: /driver-root/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: driver-root
              mountPath: /driver-root
              readOnly: true
            - name: cdi-root
              mountPath: /etc/cdi
              readOnly: true
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: driver-root
          hostPath:
            path: /
        - name: cdi-root
          hostPath:
            path: /etc/cdi
