apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  source:
    chart: gateway-helm
    repoURL: oci://docker.io/envoyproxy/gateway-helm
    targetRevision: v0.0.0-latest
    helm:
      values: |
        config:
          envoyGateway:
            provider:
              type: Kubernetes
              kubernetes: {}
            gateway:
              controllerName: gateway.envoyproxy.io/gatewayclass-controller
            logging:
              level:
                default: info
        deployment:
          envoyGateway:
            image:
              repository: docker.io/envoyproxy/gateway
              tag: v1.6.1
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 1Gi
        certgen:
          job:
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 256Mi
        topologyInjector:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
