apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway-metrics
  namespace: envoy-gateway
  labels:
    control-plane: envoy-gateway
spec:
  selector:
    matchLabels:
      control-plane: envoy-gateway
  endpoints:
  - port: metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - envoy-gateway
