apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-packages
  namespace: home-assistant
data:
  general.yaml: |
    input_boolean:
      gaming_mode:
        name: Gaming Mode
        icon: mdi:gamepad-variant
