apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drive-organizer
resources:
- namespace.yaml
- openrouter-secret.yaml
- secret-personal.yaml
- cronjob-personal.yaml
- secret-family.yaml
- cronjob-family.yaml
