apiVersion: v1
kind: Namespace
metadata:
  name: drive-organizer
  labels:
    app.kubernetes.io/name: drive-organizer
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
